### ISSUE TITLE
Issues: Nitrogen with 4 binding groups and the pdbqt generation of DNA

### ISSUE THREAD

**Issue by Johnson7L** [MatthijsHak/MetalDock#11]
Dear MatthijsHak,

When the nitrogen atom is involved with four binding groups in the ligand, the rdkit.Chem encounters difficulty in recognizing it, leading to errors. Additionally, when utilizing DNA as the targeted macromolecule, issues may arise during the generation of the clean_protein.pdbqt and clean_protein.pdb file. I will attach the input file to this chat for your reference.

[prot-ligand.zip](https://github.com/MatthijsHak/MetalDock/files/13424605/prot-ligand.zip)

Best Regards,
Z.LIN

**Comment by MatthijsHak** [comment]
Dear Z.Lin,

Your ligand.xyz has no hydrogens, so this will definitely yield erroneous results. Please try to use input structures that are physical, otherwise it will yield errors. 

Also, ground state octahedral ruthenium compounds are normally singlet, so setting the number of unpaired electrons to 5 will definitely yield some results that will be incorrect for docking purposes. 

Regards,

Matthijs
