### ISSUE TITLE
Working on metaldock: Titanium atom

### ISSUE THREAD

**Issue by Saem5075** [MatthijsHak/MetalDock#21]
Hi I am getting this type of error. I am also beginner in computational chemistry.

  File "/Users/saem/git/MetalDock/src/metal_dock/prepare_dock.py", line 577, in docking_func
    gpf.write(f'nbp_r_eps 2.20  {par.parameter_set[0]:>.4f}   12 10 NA {par.metal_symbol}\n')
TypeError: 'NoneType' object is not subscriptable

what might be the error. I would be appreciate if you get back on this. Thank you!

**Comment by MatthijsHak** [comment]
Hi, 

Can you share with me in a zip file your input file, xyz file and pdb file. I can then better deduce what the problem is.

**Comment by Saem5075** [comment]
> Hi,
> 
> Can you share with me in a zip file your input file, xyz file and pdb file. I can then better deduce what the problem is.

Thank you so much for your kind and quick response. Herewith I attached the zip file. Also I sent metaldock.dat file in which titanium atom parameters included. Thanks again!
Sincerely
Saem
[Titanium_docking.zip](https://github.com/MatthijsHak/MetalDock/files/15017317/Titanium_docking.zip)

**Comment by MatthijsHak** [comment]
Hi,

A space after Ti led to this error. I fixed this now but, unfortunately, Titanium is currently not an atom type supported by MetalDock. If you want to run it you first need to generate new parameters via the Monte Carlo optimization protocol, for which you need some reference data (protein ligand complexes).

**Comment by Saem5075** [comment]
Hi, thank you so much for your kind assistance. Sorry, I couldn't understand in which file Ti has space. It would be great if you share the corrected file or specify which one.

If MetalDock currently is not supported for Titanium, I can still use the CM5 csv file (which is generated by orca) to create pdbqt right? Thanks again!
Sincerely
Saem

**Comment by MatthijsHak** [comment]
Hi,

The empty space after metal_symbol = Ti_ (_ = space). In the new repo this should now not matter. I have looked at your calculation and ran it to made sure it generates a pdbqt file. However, you specified spin = 1, which in some QM software packages results in a singlet state, but here (see documentation) it indicates the number of spin-alpha electrons in excess of spin-beta electrons. So you would generate doublet, which I do not think you would want but correct me if I am wrong.

The QM calculation for the singlet ran just fine, and I have attached for you here the pdbqt file. If you want to use MetalDock you need to specify the following parameters under the docking header in the .ini file: e_NA, e_OA, e_SA, e_HD. Otherwise you will get a latter error.

I hope this helps. 

[titanium.pdbqt.zip](https://github.com/MatthijsHak/MetalDock/files/15061031/titanium.pdbqt.zip)

**Comment by Saem5075** [comment]
Hi,
Thank you so much for your kind help. Yes, you are absolutely right about spin, that was my mistake. Later on, I corrected spin to 0, which gave me the singlet. As of right now, I can't do Monte Carlo simulation to get e_NA, e_OA, e_SA, e_HD data, but I will use MetalDock to general the metal_complex.pdbqt file or metal_complex.mol2 file in which CM5 charge included. I am thinking to use Autodock GUI for the docking using the that files. Is this plan seems right to you? 

Also, I appreciate your valuable correction about spin. Thank you so much again!

Sincerely
Saem

**Comment by MatthijsHak** [comment]
I think that will be a viable approach. Good luck!
